# Generated by Django 4.0.6 on 2022-07-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='Replyer',
            new_name='replyer',
        ),
    ]
